export const keywords = [
  { label: 'true', description: 'Boolean true value' },
  { label: 'false', description: 'Boolean false value' },
  { label: 'and', description: 'Logical AND operator' },
  { label: 'or', description: 'Logical OR operator' },
  { label: 'not', description: 'Logical NOT operator' },
  { label: 'implies', description: 'Logical implication' },
  { label: 'equiv', description: 'Logical equivalence' },
  { label: 'forall', description: 'Universal quantifier' },
  { label: 'exists', description: 'Existential quantifier' },
  { label: 'Real', description: 'Real number type' },
  { label: 'Bool', description: 'Boolean type' },
  { label: 'HP', description: 'Hybrid program' },
  { label: 'Problem', description: 'Problem declaration' },
  { label: 'Definitions', description: 'Definitions section' },
  { label: 'ProgramVariables', description: 'Program variables section' },
  { label: 'Tactic', description: 'Tactic section' },
  { label: 'End', description: 'End of a section' },
  { label: 'ArchiveEntry', description: 'Archive entry' },
  { label: 'Theorem', description: 'Theorem declaration' },
  { label: 'Lemma', description: 'Lemma declaration' },
  { label: 'Exercise', description: 'Exercise declaration' },
  { label: 'Definition', description: 'Definition declaration' },
  { label: 'ProgramVariable', description: 'Program variable declaration' },
];

export const operators = [
  { label: '+', description: 'Addition operator' },
  { label: '-', description: 'Subtraction operator' },
  { label: '*', description: 'Multiplication operator' },
  { label: '/', description: 'Division operator' },
  { label: '^', description: 'Exponentiation operator' },
  { label: '=', description: 'Equality operator' },
  { label: '>', description: 'Greater than operator' },
  { label: '>=', description: 'Greater than or equal to operator' },
  { label: '<', description: 'Less than operator' },
  { label: '<=', description: 'Less than or equal to operator' },
  { label: '->', description: 'Implication operator' },
  { label: '<->', description: 'Equivalence operator' },
  { label: '&', description: 'Logical AND operator' },
  { label: '|', description: 'Logical OR operator' },
  { label: '!', description: 'Logical NOT operator' },
  { label: ':=', description: 'Assignment operator' },
  { label: '[', description: 'Open bracket' },
  { label: ']', description: 'Close bracket' },
  { label: '?', description: 'Conditional operator' },
];

export const functionKeywords = [
  { label: 'abs', description: 'Returns the absolute value' },
  { label: 'min', description: 'Returns the minimum value' },
  { label: 'max', description: 'Returns the maximum value' },
  { label: 'succ', description: 'Returns the successor value' },
  { label: 'gt', description: 'Returns greater than comparison' },
];

export const hybridProgramKeywords = [
  { label: 'x:=', description: 'Assignment in hybrid program' },
  { label: 'x:=*', description: 'Nondeterministic assignment in hybrid program' },
  { label: '?', description: 'Test in hybrid program' },
  { label: '++', description: 'Choice in hybrid program' },
  { label: '*', description: 'Repetition in hybrid program' },
  { label: 'x\'=', description: 'Differential equation in hybrid program' },
  { label: '&', description: 'Conjunction in hybrid program' },
];
